#!/bin/sh
# Filename:      postrm
# Purpose:       postrm script for package zsh-lovers
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Son Mai 11 10:54:57 CEST 2008 [mika]
################################################################################

#set -e
#
#case "$1" in
#    remove|purge)
#	dpkg-divert --remove --rename --package zsh-lovers --divert /usr/share/vim/syntax/zsh.vim.original \
#	/usr/share/vim/syntax/zsh.vim
#     ;;
#
#    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
#      ;;
#    *)
#      echo "postrm called with unknown argument \`$1'" >&2
#      exit 1
#esac
#
#exit 0

## END OF FILE #################################################################

#DEBHELPER#
