#!/bin/sh
# Filename:      preinst
# Purpose:       preinst script for package zsh-lovers
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Son Mai 11 10:55:11 CEST 2008 [mika]
################################################################################

#set -e
#case "$1" in
#   install|upgrade)
#        if [ -f /usr/share/vim/syntax/zsh.vim ] ; then
#           dpkg-divert --add --rename --package zsh-lovers --divert /usr/share/vim/syntax/zsh.vim.original \
#	   /usr/share/vim/syntax/zsh.vim >/dev/null
#	fi
#     ;;
#   *)
#     echo "preinst called with unknown argument \`$1'" >&2
#     exit 1
#esac
#
#exit 0

## END OF FILE #################################################################

#DEBHELPER#
